# Generated by Django 2.2.1 on 2019-05-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='first.Hashtag'),
        ),
    ]
